# Generated by Django 2.2.9 on 2020-01-22 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=500, verbose_name='First name')),
                ('first_name', models.CharField(max_length=500, verbose_name='Last name')),
                ('phone', models.CharField(max_length=500, verbose_name='Phone')),
                ('date', models.DateTimeField(verbose_name='Date of contact')),
            ],
        ),
    ]
