# Generated by Django 2.2.9 on 2020-01-22 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20200122_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='date_of_contact',
            field=models.DateField(verbose_name='Date of contact'),
        ),
    ]
